services:
  - type: web
    name: venepay
    env: python
    region: oregon
    plan: free
    repo: https://github.com/ezequielduerto-create/venepay
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: SECRET_KEY
        scope: secret
      - key: FLASK_ENV
        value: production